discount set and remove is added
CS308-Team17/online-store-backend pull request #30
Opened 2024-12-27 13:05 UTC by ozlemcaliskann

2024-12-29 10:20 UTC, gorkemtopcu commented on src/main/java/com/example/onlinestore/entity/Product.java
> +    private double originalPrice;
Sadece price ve discount olarak tutsak yeterli olmaz mi? Zaten bu ikisine bakarak yeni fiyatini hesaplayabiliriz

2024-12-29 10:22 UTC, gorkemtopcu commented on src/main/java/com/example/onlinestore/entity/Product.java
> +    }
sadece price ve discount tutarsak butun bu getOriginalPrice, setOriginalPrice, applyDiscount, removeDiscount methodlarina ihtiyacimiz kalmayacak. Zaten annotationdan gelen setter ve getterlar otomatik olarak var o yuzden ayrica get set methodlari yazmana gerek yok, applyDiscount yerine direkt olarak setDiscount calistirabilirsin, remove yapmak yerine de setDiscount(0) seklinde calistirabilirsin ayni sekilde

2024-12-29 10:25 UTC, gorkemtopcu requested changes
Eskisi gibi price kullanip sadece discount ekledigimiz takdirde daha temiz bir yapiya sahip olabilir gibi dusunuyorum, yine de commentlerim anlasilir olmadiysa birlikte de bakabiliriz buraya.

2024-12-29 14:28 UTC, ozlemcaliskann commented
düzelttim ve pushladım şuan sadece price ve discount var, teşekkürler.

2024-12-30 11:13 UTC, gorkemtopcu approved these changes

2024-12-30 11:13 UTC, merged